### ISSUE TITLE
Is Matrix in bpca() with variables in columns and observations in rows?

### ISSUE THREAD

**Issue by randel** [hredestig/pcaMethods#1]
According to the description of [`bpca()`](https://github.com/hredestig/pcaMethods/blob/master/R/bpca.R), the `Matrix` input is with variables in columns and observations in rows. But the example below and the code of `BPCA_dostep()` probably show observations in columns and variables in rows.

`pc <- pca(t(metaboliteData), method="bpca", nPcs=2)`

**Comment by hredestig** [comment]
I am not the author of `bpca` so not entirely sure, why do you think the code of `BPCA_dostep` expects observations in columns? `metaboliteData` is a dataset organized as `ExpressionSets` typically are with the variables (metabolites) in the rows and the samples in the columns so to get that to the way the `pca()` functions want it, we first transpose the data, hence the `t(metaboliteData)`

**Comment by randel** [comment]
Thanks for your work and the reply!

I compared the code with the notations in the reference Oba et al. (2003) the reference therein Bishop (1999), and the source [`Matlab` code](https://github.com/probml/pmtksupport/blob/master/bpca/BPCA_initmodel.m) I believe. There are several hints:
1) The `Matlab` code shows `[N,d] = size(y)`, while the paper uses DxN for matrix Y;
2) The demeaned y, `dy` (or `dym`, `dyo`) is always transposed in the code, while it's not transposed in the paper;
3) The missing values are imputed by rows.

The details of `metaboliteData` shows "A matrix containing 154 observations (rows) and 52 metabolites (columns)." If searching `metaboliteData` in the manual, we can find `metaboliteData` is transposed for methods `bpca` and `ppca`, but not for `llsImpute`, `svdImput`, and even the following opposites. So I guess there should be something incorrect.
`esti <- kEstimate(metaboliteData, method = "ppca", evalPcs = 2:4, nruncv=1, em="nrmsep")`
`esti <- kEstimateFast(t(metaboliteData), method = "ppca", evalPcs = 2:4, em="nrmsep")`

**Comment by Berecht** [comment]
I am also bit confused by the ppca code, if i compare it to the matlab code where it is based on. 

https://pmtk3.googlecode.com/svn-history/r2308/trunk/toolbox/LatentVariableModels/ppca/sub/ppca_mv.pdf

**Comment by hredestig** [comment]
will make an investigation asap, in the mean-time, pull-requests are of course appreciated

**Comment by randel** [comment]
Thanks! For BPCA, it may only need to change the help description or make a transpose within the function.

**Comment by hredestig** [comment]
Apologies for the incredibly slow followup. I finally looked into this
and see the reason for the confusion. In pcaMethods, we use the
convention that the PCA model as X=mu+TP'+E where T is scores matrix
and P the loadings. Observations are in rows and variables in
columns. PCA is (mostly) done on the mean-centered matrix so that mu
represents the mean values for each variable. For BPCA the situation
is the same but the original implementation uses a different
notation. The result is however the same. Let's test that.

```sh
wget http://ishiilab.jp/member/oba/tools/sources/sample999.dat
```

`sample999` has 758 rows and 50 cols.

With pcaMethods convention columns are variables as we compute their
averages and obtain those from `M.mu`.

```octave
x999 = load('sample999.dat');
[y, M] = BPCAfill(x999, k=2);
size(M.W) # 50 rows so this must be the loadings
loadings = M.W; # 50 rows
save('loadings.dat', 'loadings');
# we get the scores by matrix multiplication
scores = y * M.W;
save('scores.dat', 'scores');
```

Check similarity in R, loadings / scores can be rotated without any
difference to the result


```r
mat <- as.matrix(read.table("sample999.dat"))
mat[(mat - 999)^2 < 1e-4] <- NA
pc <- pca(mat, method="bpca", verbose=FALSE)
dim(loadings(pc))
```

```
## [1] 50  2
```

```r
octload <- as.matrix(read.table("loadings.dat"))
octscores <- as.matrix(read.table("scores.dat"))
cor(octload, loadings(pc))
```

```
##         PC1       PC2
## V1 1.000000 -0.017361
## V2 0.017293 -1.000000
```

```r
cor(octscores, scores(pc))
```

```
##           PC1         PC2
## V1 1.00000000 -0.00014171
## V2 0.00022622 -0.99999999
```

Result is the same. However, the
[BPCA matlab documentation](http://ishiilab.jp/member/oba/tools/BPCAFill.html)
clearly indicates that the input matrix is to be 'genes' (mostly
interpreted as variables) x 'samples'. From that follows that BPCA in
the matlab version simply switches the concept of variable and sample
compared to the interpretation in pcaMethods. From the point of
missing value estimation, one might get good results that way as well,
as BPCA test also has clearly shown but for interpretation is it a bit
unusual. For the sake of not causing confusion compared to how other
pcaMethods work, we do not adopt the BPCA style but leave the option
to transpose the input matrix to the user instead.

In pcaMethods 1.60.2 this is now further emphasized in `?bpca`
